[package]
name = "tyran"
version = "0.1.0"
authors = ["Payton Turnage <paytonturnage@gmail.com>"]
build = "build.rs"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = true

[dependencies]
